name: artifact workflow
on:  
  workflow_dispatch:
  
jobs:
  artifact-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: "Check file existence"
        run: '(test -f crowdin.yml && echo crowdin exists) || echo crowdin does not exist, skipping step'

      - name: Checkout v2
        uses: actions/checkout@v2
        
      - name: Git actions
        run: |
          git fetch
          git diff fd4833e5123dc0a30081ca1ab1d8626746dad73d f02a364 -- locales-json/en.json -U0 > artifacts/git-diff.txt

#     - uses: actions/upload-artifact@v2
#       with:
#         name: my-artifact
#         path: artifacts/git-diff.txt
