name: Share data between jobs

on:
  workflow_dispatch:

jobs:
  job_1:
    name: Git Diff Fetch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout v2
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
        
      - name: Git actions
        run: git fetch
        
      - name: Git Diff
        run: |
          git diff fd4833e5123dc0a30081ca1ab1d8626746dad73d f02a364 -- locales-json/en.json -U0 | grep '^[+]' | grep -Ev '^(--- a/|\+\+\+ b/)' > git-diff.txt

      - name: Upload git diff artifact
        uses: actions/upload-artifact@v2
        with:
          name: gitdiff
          path: git-diff.txt

  job_3:
    name: Display results
    needs: job_1
    runs-on: ubuntu-latest
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v2
        with:
          name: gitdiff

      - name: Filter strings
        run: |
          arr1=()
          queryString=""
          while IFS= read -r line; do
            arr1+=($(echo "$line" | grep -o -m1 '".*"' | cut -d: -f1))
          done < git-diff.txt
          for each in "${arr1[@]}"
          do
           queryString+="identifier=.$each and "
          done
          output1=$( jq -nRr --arg s "$queryString" '$s|@uri')
          echo "https://api.crowdin.com/api/v2/projects/480641/strings?croql=${output1/%?????/}"
          
#       - name: Get All Strings
#         id: strings-list
#         uses: satak/webrequest-action@master
#         with:
#           url: https://api.crowdin.com/api/v2/projects/480641/strings
#           method: GET
#           headers: '{"Authorization": "Bearer ${{ secrets.CROWDIN_PERSONAL_TOKEN }}"}'

#       - name: Print the final result
#         shell: bash
#         run: |
#           cat git-diff.txt
