name: artifact workflow
on:  
  workflow_dispatch:
  
jobs:
  artifact-workflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: |
        FILE=/artifacts/git-diff.txt
        if test -f "$FILE"; then
          echo "$FILE exists."
        fi
    - run: git fetch
    - run: git diff fd4833e5123dc0a30081ca1ab1d8626746dad73d f02a364 -- locales-json/en.json -U0 > artifacts/git-diff.txt

#     - uses: actions/upload-artifact@v2
#       with:
#         name: my-artifact
#         path: artifacts/git-diff.txt
