name: Share data between jobs

on:
  workflow_dispatch:

jobs:
  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - name: Checkout v2
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
        
      - name: Git actions
        run: git fetch
        
      - name: Git Diff
        run: |
          git diff fd4833e5123dc0a30081ca1ab1d8626746dad73d f02a364 -- locales-json/en.json -U0 > git-diff.txt

      - name: Upload git diff artifact
        uses: actions/upload-artifact@v2
        with:
          name: gitdiff
          path: git-diff.txt

  job_3:
    name: Display results
    needs: job_1
    runs-on: ubuntu-latest
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v2
        with:
          name: gitdiff
      - name: Print the final result
        shell: bash
        run: |
          value=`cat git-diff.txt`
          echo $value
