name: dumy workflow
on:
  push:
    branches: [ main ]
    paths:
    - 'locales-json/en.json'
  
  workflow_dispatch:

jobs:
  dummy-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

#       - name: Get changed files
#         id: changed-files
#         uses: tj-actions/changed-files@v10

#       - name: crowdin action
#         uses: crowdin/github-action@1.4.0
#         with:
#           upload_sources: true
#           download_translations: true
#           localization_branch_name: 'translations_branch'
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
#           CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          
      - name: Get All Strings
        id: strings-list
        uses: satak/webrequest-action@master
        with:
          url: https://api.crowdin.com/api/v2/projects/480641/strings
          method: GET
          headers: '{"Authorization": "Bearer ${{ secrets.CROWDIN_PERSONAL_TOKEN }}"}'
       
      - name: List all strings
        run: |
          echo '{"url":"https://api.crowdin.com/api/v2/projects/480641/strings","method":"get","payload":null,"time":"17:20:45 GMT+0000 (Coordinated Universal Time)","statusCode":200,"data":{"data":[{"data":{"id":1,"projectId":480641,"fileId":1,"branchId":null,"directoryId":null,"identifier":".testdup","text":"testdup","type":"text","context":" -> testdup","maxLength":0,"isHidden":false,"revision":4,"hasPlurals":false,"isIcu":false,"labelIds":[],"createdAt":"2021-10-15T05:06:28+00:00","updatedAt":null}},{"data":{"id":3,"projectId":480641,"fileId":1,"branchId":null,"directoryId":null,"identifier":".test12","text":"test1","type":"text","context":" -> test12","maxLength":0,"isHidden":false,"revision":4,"hasPlurals":false,"isIcu":false,"labelIds":[],"createdAt":"2021-10-15T05:06:28+00:00","updatedAt":null}},{"data":{"id":5,"projectId":480641,"fileId":1,"branchId":null,"directoryId":null,"identifier":".test2","text":"test4","type":"text","context":" -> test2","maxLength":0,"isHidden":false,"revision":4,"hasPlurals":false,"isIcu":false,"labelIds":[],"createdAt":"2021-10-15T05:06:28+00:00","updatedAt":null}},{"data":{"id":7,"projectId":480641,"fileId":1,"branchId":null,"directoryId":null,"identifier":".test3","text":"test32","type":"text","context":" -> test3","maxLength":0,"isHidden":false,"revision":4,"hasPlurals":false,"isIcu":false,"labelIds":[],"createdAt":"2021-10-15T05:06:28+00:00","updatedAt":null}},{"data":{"id":9,"projectId":480641,"fileId":1,"branchId":null,"directoryId":null,"identifier":".test4","text":"test34","type":"text","context":" -> test4","maxLength":0,"isHidden":false,"revision":4,"hasPlurals":false,"isIcu":false,"labelIds":[],"createdAt":"2021-10-15T05:06:28+00:00","updatedAt":null}},{"data":{"id":11,"projectId":480641,"fileId":1,"branchId":null,"directoryId":null,"identifier":".test5","text":"testaasdad","type":"text","context":" -> test5","maxLength":0,"isHidden":false,"revision":4,"hasPlurals":false,"isIcu":false,"labelIds":[],"createdAt":"2021-10-15T05:06:28+00:00","updatedAt":null}},{"data":{"id":13,"projectId":480641,"fileId":1,"branchId":null,"directoryId":null,"identifier":".test6","text":"test6asdas","type":"text","context":" -> test6","maxLength":0,"isHidden":false,"revision":4,"hasPlurals":false,"isIcu":false,"labelIds":[],"createdAt":"2021-10-15T05:06:28+00:00","updatedAt":null}},{"data":{"id":15,"projectId":480641,"fileId":1,"branchId":null,"directoryId":null,"identifier":".test43","text":"test343asdadasdads","type":"text","context":" -> test43","maxLength":0,"isHidden":false,"revision":4,"hasPlurals":false,"isIcu":false,"labelIds":[],"createdAt":"2021-10-15T05:06:28+00:00","updatedAt":null}},{"data":{"id":19,"projectId":480641,"fileId":1,"branchId":null,"directoryId":null,"identifier":".test32322","text":"tesopaodasdas","type":"text","context":" -> test32322","maxLength":0,"isHidden":false,"revision":4,"hasPlurals":false,"isIcu":false,"labelIds":[],"createdAt":"2021-10-20T13:56:39+00:00","updatedAt":null}},{"data":{"id":21,"projectId":480641,"fileId":1,"branchId":null,"directoryId":null,"identifier":".asdasdasd","text":"asdadads","type":"text","context":" -> asdasdasd","maxLength":0,"isHidden":false,"revision":4,"hasPlurals":false,"isIcu":false,"labelIds":[],"createdAt":"2021-10-20T14:03:39+00:00","updatedAt":null}},{"data":{"id":23,"projectId":480641,"fileId":1,"branchId":null,"directoryId":null,"identifier":".Another","text":"Anotherone","type":"text","context":" -> Another","maxLength":0,"isHidden":false,"revision":4,"hasPlurals":false,"isIcu":false,"labelIds":[],"createdAt":"2021-10-20T14:07:09+00:00","updatedAt":null}}],"pagination":{"offset":0,"limit":25}}}' | jq '.url'
#          $outputVar='${{ steps.strings-list.outputs.output }}' | jq '.url'
#          echo "$outputVar"
#       - name: List all modified files
#         run: |
#           for file in "${{ steps.changed-files.outputs.all_modified_files }}"; do
#             echo "$file was modified"
#           done
