name: crowdin-download-pr workflow
on:
  workflow_dispatch:

jobs:
  crowdin-dwnld-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Run Scripts
        shell: bash
        working-directory: crowdin
        run: |
          cd ./js && npm install && cd ..
          node js/index.js ${{ secrets.CROWDIN_PROJECT_ID }} ${{ secrets.CROWDIN_PERSONAL_TOKEN }} && rm ./js/package-lock.json

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H_%M_%S')"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Translation Updates from Crowdin
          title: Translation Updates from Crowdin
          body: Translation Updates from Crowdin
          branch: translation-updates-${{ steps.date.outputs.date }}
  
  # create-pr-job:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0

      # - name: Script data
      #   shell: bash
      #   working-directory: crowdin
      #   run: |
      #      chmod +x crowdin_init.sh
      #      ./crowdin_init.sh ${{ secrets.CROWDIN_PROJECT_ID }} ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
