name: crowdin-download-pr workflow
on:
  workflow_dispatch:

jobs:
  crw-dwn-pr-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Script data
        shell: bash
        working-directory: crowdin
        run: |
           chmod +x crowdin_init.sh
           ./crowdin_init.sh ${{ secrets.CROWDIN_PROJECT_ID }} ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: JSON Changes
          title: Update JSON FILEs
          body: Testing JSON Files
          branch: json-updates
