name: crowdin-download-pr workflow
on:
  workflow_dispatch:

jobs:
  crowdin-dwnld-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Run Scripts
        shell: bash
        working-directory: crowdin
        run: |
          cd ./js && npm install && cd ..
          node js/index.js ${{ secrets.CROWDIN_PROJECT_ID }} ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
  
  create-pr-job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: JSON Changes
          title: Update JSON FILEs
          body: Testing JSON Files
          branch: json-updates

      # - name: Script data
      #   shell: bash
      #   working-directory: crowdin
      #   run: |
      #      chmod +x crowdin_init.sh
      #      ./crowdin_init.sh ${{ secrets.CROWDIN_PROJECT_ID }} ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
