name: yaml file workflow
on:
  push:
    branches: [ main ]
    paths:
    - 'locales-json/en.yml'
  
  workflow_dispatch:

jobs:
  yml-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.13.5
        
      - name: Print yaml key
        working-directory: locales-yml
        run: yq eval -o=p en.yml
#         run: cat test.yml | yq e '.en.time.am'
#         run: echo {{ yq e '.en.time.am' ../locales-json/en.yaml }}
